config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :tasks do
    member do
      patch :toggle_status
    end
  end

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
require "open-uri"

class Task < ApplicationRecord
  after_save if: -> { saved_change_to_title? } do
    set_photo
  end

  has_one_attached :photo
  validates :title, :status, :due, presence: true
  validates :status, inclusion: { in: ["Completed", "In Progress"] }
  scope :in_progress, -> { where(status: "In Progress") }
  scope :completed, -> { where(status: "Completed") }

  after_create_commit -> { broadcast_append_to "tasks", target: "tasks-list" }

  private

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "due", "id", "id_value", "status", "title", "updated_at"]
  end

  def set_photo
    TaskPhotoJob.perform_later(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @q_in_progress = Task.in_progress.ransack(params[:q_in_progress])
    @in_progress = @q_in_progress.result
    @q_completed = Task.completed.ransack(params[:q_completed])
    @completed = @q_completed.result
    Rails.logger.debug "Params: #{params.inspect}"
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    TaskPhotoJob.perform_later(@task.id)

    respond_to do |format|
      if @task.save
        format.turbo_stream
        format.html { redirect_to tasks_path, notice: "Task was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to root_path
  end

  def toggle_status
    @task = Task.find(params[:id])
    @task.update(status: params[:status])
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tasks_path, notice: 'Task updated.' }
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :due)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <div id="modals"></div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tasks/_banner.html.erb
<div class="banner">
  <div class="banner-container">
    <h1 class="banner-text">
      tasku
    </h1>
  </div>
</div>

app/views/tasks/_completed_task_overlay.html.erb
<div class="card task-card">
  <div class="card-front">
    <%= cl_image_tag task.photo.key, class: "card-img", alt: "AI-generated image of the task" if task.photo.attached? %>
    <div class="card-img-overlay">
      <div class="card-right">
        <span class="due-date">
          <%= task.due.strftime('%b %e, %Y') %>
        </span>
        <span class="task-name">
          <h2 id="title"><%= task.title %></h2>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= turbo_frame_tag "modal_task_form_#{task.id}" do %>
  <%= simple_form_for task do |f| %>
    <div class="text-center">
      <div class="modal-header">
        <h5 class="modal-title">Edit Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :status, collection: ["Completed", "In Progress"] %>
        <%= f.input :due, input_html: { data: { controller: "datepicker" } } %>
        <%= f.button :submit, class: "btn btn-task" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tasks/_search_form.html.erb
<%= search_form_for q do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont, class: "form-control" %>
  <%= link_to "Clear", request.path, class: "btn btn-default" %>
  <%= f.submit %>
<% end %>
<div class="sorting-buttons">
  <button class="btn-sort">
    <%= sort_link(q, :title) %>
  </button>
  <button class="btn-sort">
    <%= sort_link(q, :due) %>
  </button>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>">
  <div class="card-front">
    <%= turbo_stream_from "task_channel" %>
    <div class="image">
      <% if task.photo.attached? %>
        <%= cl_image_tag(task.photo.key, class: "card-img", alt: "AI-generated image of the task") %>
      <% else %>
        <%= "loading image" %>
      <% end %>
    </div>
    <div class="card-img-overlay">
      <div class="card-icons">
        <i class="icon fa-solid fa-pen-to-square fa-xl text-dark" data-bs-toggle="modal" data-bs-target="#updateModal-<%= task.id %>"></i>
        <%= link_to task_path(task), class: "text-dark", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="icon fa-solid fa-trash fa-xl"></i>
        <% end %>
      </div>
      <div class="card-right">
        <span class="due-date">
          Due: <%= task.due.strftime('%b %e, %Y') %>
          <%= form_with url: toggle_status_task_path(task), method: :patch, data: { turbo: true } do |f| %>
            <%= f.check_box :status,
                  {
                    checked: task.status == 'Completed',
                    onchange: 'this.form.submit();',
                  },
                    "Completed",
                    "In Progress" %>
            <%= f.label :status, "Completed" %>
          <% end %>
        </span>
        <span class="task-name">
          <h2 id="title"><%= task.title.titleize %></h2>
        </span>
      </div>
    </div>
  </div>

  <%# edit task modal %>
  <div class="modal fade" id="updateModal-<%= task.id %>" tabindex="-1" aria-labelledby="updateModalLabel-<%= task.id %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= turbo_frame_tag "modal_task_form_#{task.id}" do %>
          <%= render "tasks/form", task: task %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/create.turbo_stream.erb.erb
<%= turbo_stream.append "tasks-list" do %>
  <%= render "task", task: @task %>
<% end %>

<%# <turbo-stream action="append" target="modals">
  <template>
    <script>
      const modal = bootstrap.Modal.getInstance(document.getElementById("newTaskModal"));
      if (modal) modal.hide();
    </script>
  </template>
</turbo-stream> %>

app/views/tasks/edit.html.erb
 <%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :status, collection: ["Completed", "In Progress", "Not Started"] %>
  <%= f.input :due, as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.button :submit, class: "btn btn-task" %>
<% end %>

app/views/tasks/index.html.erb
<%= render "banner" %>

<div class="container home-page">
  <div class="row">
    <div class="col-4 all-tasks border-end border-dark">
      <h2 class="section-head">Tasks in progress...</h2>
      <div class="search">
        <%= render "search_form", q: @q_in_progress %>
      </div>
      <%= turbo_stream_from "tasks" %>
      <div id="tasks-list" class="task-cards">
        <% if @in_progress.length > 0 %>
          <% @in_progress.each do |task| %>
            <% if task.status == "In Progress" %>
              <div class="card task-card">
                <%= render "task", task: task %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="text-center">
            <h2>add a task...</h2>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-4 completed-tasks border-end border-dark">
      <div class="task-cards">
        <h2 class="section-head">Completed tasks...</h2>
        <div class="search">
          <%= render "search_form", q: @q_completed %>
        </div>
        <% @completed.each do |done| %>
          <div class="card task-done-card text-white">
            <%= render "task", task: done %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <div class="new-task my-3">
        <%= turbo_frame_tag :individual_task do %>
          <div class="new-button">
            <%= link_to "new task", new_task_path, class: "btn btn-task btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag :individual_task do %>
  <div class="container new-page text-center">
    <%= simple_form_for @task, data: { turbo_stream: true }, html: { data: { turbo_frame: "individual_task" } } do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :status, collection: ["In Progress", "Completed"] %>
      <%= f.input :due, as: :string, input_html: { data: { controller: "datepicker" } } %>
      <%= f.button :submit, class: "btn btn-task" %>
    <% end %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="card task-cards">
  <span class="task-name">
    <%= @task.description %>
  </span>
</div>